hw07_file_copying
razielsd/otus_hw_test pull request #6
Opened 2021-07-11 17:36 UTC by razielsd

## Домашнее задание №7 «Утилита для копирования файлов»

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2021-07-13 15:42 UTC, Antonboom requested changes
https://otus.ru/teacher-lk/homework/157684/9790/

Здравствуйте!
Хорошая работа, хотелось бы чуть дожать.

Спасибо

2021-07-13 15:42 UTC, Antonboom commented on hw07_file_copying/copy.go
> +		return err
повсеместно не хватает врапинга
```
return fmt.Errorf("cannot open file: %v")
return fmt.Errorf("%w: %v", ErrorUnableGetStat, err)
```

вы теряете текст оригинальной ошибки - тяжело её будет дебажить

2021-07-13 15:42 UTC, Antonboom commented on hw07_file_copying/copy.go
> +	bar.Finish()
делать через defer

2021-07-13 15:42 UTC, Antonboom commented on hw07_file_copying/copy.go
> +	for cpsize < limit {
чем вызвано желание читать поблочно?

почему нельзя один раз заиспользовать `io.Copy`?

2021-07-13 15:42 UTC, Antonboom commented on hw07_file_copying/copy.go
> +func GetBlockSize(limit int64) (int64, error) {
почему экспортируется?

2021-07-13 15:42 UTC, Antonboom commented on hw07_file_copying/copy.go
> +	BlockCount   = 100
их надо экспортировать?

2021-07-13 15:42 UTC, Antonboom commented on hw07_file_copying/copy_test.go
> +	require.Equal(t, ErrorEmptySourcePath, err)
```
require.ErrorIs
```
везде

2021-07-13 15:42 UTC, Antonboom commented on hw07_file_copying/copy_test.go
> +import (
а где собственно позитивные тесты на копирование?

2021-07-13 15:42 UTC, Antonboom commented on hw07_file_copying/main.go
> +		switch {
есть ли в нём смысл? почему бы просто не напечатать ошибку и выйти?

2021-07-13 15:48 UTC, razielsd commented on hw07_file_copying/main.go
> +		switch {
мое чисто субъективное мнение: на мой взгляд так красивее

2021-07-13 15:50 UTC, razielsd commented on hw07_file_copying/copy.go
> +	for cpsize < limit {
это артефакт того, что разбирался как сделать прогресбар, сейчас в этом нет смысла

2021-07-13 15:53 UTC, razielsd commented on hw07_file_copying/copy_test.go
> +import (
в корне лежит test.sh, мне кажется что его достаточно для этой задачи

2021-07-15 16:21 UTC, Antonboom submitted a review, later dismissed
Принято
8 / 10

2021-07-15 16:21 UTC, Antonboom commented on hw07_file_copying/copy.go
> +	ErrorEmptySourcePath      = errors.New("empty source path")
FYI: нейминг ошибок обычно

- если переменная Err* (не Error)
- если тип myError (не Err)

2021-07-15 16:21 UTC, Antonboom commented on hw07_file_copying/copy.go
> +	buff := make([]byte, limit)
а можно обойтись без лишних аллокаций?

2021-07-15 16:21 UTC, Antonboom commented on hw07_file_copying/copy.go
> +	buff := make([]byte, limit)
Seek + LimitedReader ?

2021-07-15 16:21 UTC, Antonboom commented on hw07_file_copying/copy.go
> +		return err
нет врапинга здесь и ниже

2021-07-15 16:21 UTC, Antonboom commented on hw07_file_copying/copy_test.go
> +			ok, err := readercomp.FilesEqual(tc.expected, dest)
A little copying is better than a little dependency.

а тут и копирование не нужно, странно, что вы сами код не написали

2021-07-15 16:39 UTC, razielsd commented on hw07_file_copying/copy.go
> +	ErrorEmptySourcePath      = errors.New("empty source path")
fixed

2021-07-15 16:48 UTC, razielsd commented on hw07_file_copying/copy.go
> +		return err
fixed

2021-07-15 19:36 UTC, razielsd commented on hw07_file_copying/copy_test.go
> +			ok, err := readercomp.FilesEqual(tc.expected, dest)
ок, выпилил

2021-07-16 07:37 UTC, Antonboom submitted a review, later dismissed
Получилось очень хорошо. Сравните с первым вариантом :)

2021-07-16 07:37 UTC, Antonboom commented on hw07_file_copying/copy_test.go
> +			dest := t.TempDir() + "/" + tc.dest + ".txt"
filepath.Join

2021-07-16 10:41 UTC, razielsd commented on hw07_file_copying/copy_test.go
> +			dest := t.TempDir() + "/" + tc.dest + ".txt"
fixed

2021-07-16 10:53 UTC, Antonboom approved these changes
Принято
10 / 10

2021-07-16 10:54 UTC, merged