hw10_program_optimization
razielsd/otus_hw_test pull request #7
Opened 2021-07-11 21:01 UTC by razielsd

## Домашнее задание №10 «Оптимизация программы»

### Критерии оценки
- [ ] Пайплайн зелёный и нет попытки «обмануть» систему - 4 балла
- [ ] Добавлены юнит-тесты - до 3 баллов
- [ ] Понятность и чистота кода - до 3 баллов

#### Зачёт от 7 баллов

2021-07-12 16:01 UTC, agneum requested changes
Добрый вечер.
Спасибо за вариант решения. Предлагаю всё же ускорить анмаршаллинг

См. [частые ошибки](https://github.com/razielsd/otus_hw_test/tree/hw10_program_optimization/hw10_program_optimization#%D1%87%D0%B0%D1%81%D1%82%D1%8B%D0%B5-%D0%BE%D1%88%D0%B8%D0%B1%D0%BA%D0%B8):

> Работа с сырыми байтами, нахождение позиции "Email" и пр. вместо ускорения анмаршалинга более поддерживаемыми и понятными средствами.

В качестве таких библиотек могут быть: 
https://github.com/json-iterator/go
https://github.com/mailru/easyjson и т.д.

2021-07-12 18:00 UTC, razielsd commented
> Добрый вечер.
> Спасибо за вариант решения. Предлагаю всё же ускорить анмаршаллинг
> 
> См. [частые ошибки](https://github.com/razielsd/otus_hw_test/tree/hw10_program_optimization/hw10_program_optimization#%D1%87%D0%B0%D1%81%D1%82%D1%8B%D0%B5-%D0%BE%D1%88%D0%B8%D0%B1%D0%BA%D0%B8):
> 
> > Работа с сырыми байтами, нахождение позиции "Email" и пр. вместо ускорения анмаршалинга более поддерживаемыми и понятными средствами.
> 
> В качестве таких библиотек могут быть:
> https://github.com/json-iterator/go
> https://github.com/mailru/easyjson и т.д.

готово, сделал через fastjson, только через вышеуказанные библиотеки не получилось, по памяти не проходили тесты или я что-то делал не так :(

2021-07-13 16:40 UTC, agneum submitted a review, later dismissed
Спасибо за правки. Хорошая работа.
Итого: 9 баллов из 10

2021-07-13 16:40 UTC, agneum commented on hw10_program_optimization/stats.go
> +	if err := fastjson.ValidateBytes(line); err != nil {
Думаю, что валидацию всей строки можно пропустить - интересен только email.

В библиотеке есть список рекомендаций для performance: https://github.com/valyala/fastjson#performance-optimization-tips

2021-07-13 16:40 UTC, agneum commented on hw10_program_optimization/stats.go
> +	extractor := GetHostExtractor(domain)
За один вызов проверяется один домен. 
Думаю, что можно реализовать без замыкания, максимально просто подсчитывая количество адресов

2021-07-13 17:03 UTC, razielsd commented on hw10_program_optimization/stats.go
> +	extractor := GetHostExtractor(domain)
убрал замыкание

2021-07-16 12:25 UTC, agneum commented on hw10_program_optimization/stats.go
> +	extractor := GetHostExtractor(domain)
Спасибо за правки. 
10/10

2021-07-16 12:25 UTC, agneum approved these changes

2021-07-16 12:28 UTC, merged