hw06_pipeline_execution
razielsd/otus_hw_test pull request #9
Opened 2021-08-12 13:44 UTC by razielsd

## Домашнее задание №6 «Пайплайн»

### Критерии оценки
- [ ] CI-пайплайн зелёный - 5 баллов
- [ ] Добавлены новые юнит-тесты - до 2 баллов
- [ ] Понятность и чистота кода - до 3 баллов

#### Зачёт от 7 баллов

2021-08-17 15:12 UTC, Antonboom requested changes
https://otus.ru/teacher-lk/homework/157684/9801/

Здравствуйте!
Смогём сделать почище?

2021-08-17 15:12 UTC, Antonboom commented on hw06_pipeline_execution/pipeline.go
> +			// в принципе можно без селекта, но если не закроют канал, тогда горутина так и останется
в том-то и дело, что без селекта нельзя )

2021-08-17 15:12 UTC, Antonboom commented on hw06_pipeline_execution/pipeline.go
> +					sin <- v
забыли селект?

2021-08-17 15:12 UTC, Antonboom commented on hw06_pipeline_execution/pipeline.go
> +	go func() {
в задаче достаточно по 1 горутине на каждый stage, тут явно больше

наблюдается лишний код, хотя достаточно пройтись циклом по стейджам и запустить воркеры-перекладывалки

2021-08-19 09:48 UTC, razielsd commented on hw06_pipeline_execution/pipeline.go
> +			// в принципе можно без селекта, но если не закроют канал, тогда горутина так и останется
оставил только селект

2021-08-19 09:49 UTC, razielsd commented on hw06_pipeline_execution/pipeline.go
> +					sin <- v
да, fixed

2021-08-19 09:49 UTC, razielsd commented on hw06_pipeline_execution/pipeline.go
> +	go func() {
убрал, но тогда не получается закрывать каналы там, где открываю

2021-08-23 06:15 UTC, Antonboom requested changes

2021-08-23 06:15 UTC, Antonboom commented on hw06_pipeline_execution/pipeline.go
> +	go func() {
а зачем вам эта горутина?

почему нельзя просто сразу вернуть out?

2021-08-23 06:15 UTC, Antonboom commented on hw06_pipeline_execution/pipeline.go
> +				case pineIn <- v:
нужна ли  этадополнительная перекладывалка?

по идее цикла выше достаточно, если грамотно менять in/out каналы

2021-08-27 07:12 UTC, Antonboom approved these changes
Браво!

2021-08-27 07:25 UTC, merged